problem_statement:
  description: "Manual PR reviews are time-consuming and inconsistent"
  pain_points:
    - "Security vulnerabilities missed in reviews"
    - "Incomplete PR descriptions"
    - "Inconsistent review standards"
    - "Time spent on repetitive review tasks"
    - "Missing test documentation"

solution_overview:
  product_name: "Yama"
  value_proposition: "AI-powered automated PR analysis with consensus-based multi-instance processing and intelligent deduplication"
  key_benefits:
    - "80% reduction in manual review time"
    - "100% coverage of security patterns"
    - "Consistent PR documentation"
    - "Actionable inline feedback"
    - "Enhanced accuracy through multi-instance AI consensus"
    - "Reduced noise via intelligent deduplication"
    - "Optimal performance through parallel processing"
    - "Fault tolerance and redundancy"

user_personas:
  - name: "Senior Developer"
    needs:
      - "Fast security vulnerability detection"
      - "Code quality insights"
      - "Time savings on reviews"
    how_yama_helps:
      - "Automated security analysis"
      - "Inline suggestions"
      - "Focus on complex logic review"

  - name: "Team Lead"
    needs:
      - "Consistent review standards"
      - "Complete PR documentation"
      - "Team productivity metrics"
    how_yama_helps:
      - "Enforces coding standards"
      - "Ensures required sections in PRs"
      - "Analytics on code quality trends"

  - name: "DevOps Engineer"
    needs:
      - "CI/CD integration"
      - "Automated quality gates"
      - "Configuration management"
    how_yama_helps:
      - "CLI for pipeline integration"
      - "Configurable quality thresholds"
      - "YAML-based configuration"

user_workflows:
  manual_review:
    description: "Developer runs Yama before requesting review"
    steps:
      - "Create PR in Bitbucket"
      - "Run: yama guardian --review --enhance"
      - "Review AI feedback"
      - "Fix critical issues"
      - "Request human review"

  automated_pipeline:
    description: "CI/CD runs Yama on every PR"
    steps:
      - "PR created/updated triggers pipeline"
      - "Pipeline runs Yama analysis"
      - "Comments posted to PR"
      - "Quality gates enforced"

feature_highlights:
  code_review:
    description: "AI-powered security and quality analysis"
    capabilities:
      - "Security vulnerability detection"
      - "Performance issue identification"
      - "Code quality assessment"
      - "Inline comment posting"
    severities: ["CRITICAL", "MAJOR", "MINOR", "SUGGESTION"]

  multi_instance_processing:
    description: "Consensus-based analysis using multiple AI instances"
    capabilities:
      - "Parallel execution of multiple AI models"
      - "Instance-specific configurations (provider, model, temperature)"
      - "Consensus-based result aggregation"
      - "Fault tolerance through redundancy"
      - "Enhanced accuracy through diverse perspectives"

  advanced_deduplication:
    description: "Multi-level intelligent deduplication system"
    capabilities:
      - "Exact hash-based duplicate removal"
      - "Normalized content duplicate elimination"
      - "Same file+line duplicate resolution with severity prioritization"
      - "AI-powered semantic similarity analysis"
      - "Prevention of redundant comments on existing PR discussions"

  parallel_processing:
    description: "Sophisticated resource management and concurrency control"
    capabilities:
      - "Semaphore-based concurrency control"
      - "Token budget management and allocation"
      - "Optimal concurrency calculation"
      - "Graceful error handling and recovery"
      - "Comprehensive resource utilization monitoring"

  description_enhancement:
    description: "Automatic PR description improvement"
    capabilities:
      - "Adds missing required sections"
      - "Preserves existing content"
      - "Generates test documentation"
      - "Creates comprehensive changelogs"
    required_sections:
      - "Changelog (Modules Modified)"
      - "Test Cases (What to be tested)"
      - "Config Changes"

success_metrics:
  efficiency:
    - "90% reduction in API calls via caching"
    - "80% reduction in review time"
    - "100% PR documentation compliance"

  quality:
    - "Zero missed security patterns"
    - "Consistent review standards"
    - "Improved code quality scores"

  adoption:
    - "Easy CLI integration"
    - "Minimal configuration required"
    - "Works with existing workflows"

competitive_advantages:
  - "Unified context gathering (vs separate API calls)"
  - "Smart diff strategies for large PRs"
  - "Content preservation in enhancements"
  - "Configurable quality standards"
  - "Enterprise Bitbucket support"
  - "Multi-instance consensus-based AI analysis (vs single AI model)"
  - "Advanced 4-level deduplication system (vs basic duplicate removal)"
  - "AI-powered semantic similarity analysis for intelligent comment filtering"
  - "Sophisticated parallel processing with resource management"
  - "Fault tolerance through instance redundancy and graceful error handling"
  - "Comprehensive token budget management across multiple AI providers"
  - "Security-first file prioritization for critical vulnerability detection"
